### ISSUE TITLE
All attached props are deleted

### ISSUE THREAD

**Issue by OpheliaRedRose** [jimathy/jim-consumables#1]
While using this, I realized that when you finish eating, it deletes all props attached by scripts. I'm using a weapons on back script, and the weapons are deleted as well as the prop.

**Comment by jimathy** [comment]
Oh interesting. Yea, I can see why this would happen...I need to work out a way to stop it..I'll look into this

**Comment by jimathy** [comment]
try the latest version and let me know if everything is removed correctly

It should only do the prop that's been created now, but I'm hoping it does THAT correctly

**Comment by OpheliaRedRose** [comment]
Works perfect now! Appreciate it!
